version: '3'
services:
  web:
    container_name: web
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' # -e production
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      RAILS_ENV: development
  db:
    container_name: db
    image: "mysql:5.7"
    volumes:
    - ./db/database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: e9972b2dbcc9533158f71da18c790b02
    ports:
      - "3307:3306"