default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: e9972b2dbcc9533158f71da18c790b02
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  timeout: 5000
  host: db
  
development:
  <<: *default
  database: qandam_development

test:
  <<: *default
  database: qandam_test

production:
  <<: *default
  database: qandam_production
  username: qandam
  password: <%= ENV['QANDAM_DATABASE_PASSWORD'] %>