default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  database: qandam
  username: root
  password: e9972b2dbcc9533158f71da18c790b02
  host: db
  port: 3306
development:
  <<: *default
  database: qandam_development

test:
  <<: *default
  database: qandam_test

production:
  <<: *default
  database: qandam_production

